spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restapi?useTimezone=true&serverTimezone=UTC
    username: root
    password: 860808
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  #properties:
   # hibernate:
    #  dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
